# Generated by Django 6.0.5 on 2026-05-24 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_pl', models.CharField(max_length=120, verbose_name='Nazwa (PL)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, verbose_name='Opis / funkcje')),
                ('price_pln', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (PLN)')),
                ('power_watts', models.PositiveIntegerField(default=0, help_text='Dla zasilacza: moc nominalna (W).', verbose_name='Pobór mocy (W)')),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='builder.category')),
            ],
            options={
                'verbose_name': 'Komponent',
                'verbose_name_plural': 'Komponenty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mój zestaw', max_length=160)),
                ('components', models.JSONField(default=dict, help_text='Mapa slug_kategorii -> id komponentu')),
                ('total_price_pln', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_power_w', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zapisany zestaw',
                'verbose_name_plural': 'Zapisane zestawy',
                'ordering': ['-updated_at'],
            },
        ),
    ]
